version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults
    steps:
      - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  app-testing:
    jobs:
      - test
